#!/usr/bin/env python3
"""Generate claims/claim-registry.v1.json from frozen module text."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "phase2" / "src"))
import claims as phase2_claims  # noqa: E402


def claim(
    claim_id: str,
    *,
    title: str,
    proposition: str,
    module: str,
    profiles: list[str],
    checks: list[str],
    evidence: list[str],
    does_not: list[str],
    trust: list[str] | None = None,
    aliases: list[str] | None = None,
    notes: str | None = None,
    status: str = "active",
) -> dict:
    item = {
        "claimId": claim_id,
        "claimVersion": "1",
        "title": title,
        "proposition": proposition,
        "module": module,
        "profileVersions": profiles,
        "requiredChecks": checks,
        "requiredEvidence": evidence,
        "trustAssumptions": trust or [],
        "doesNotEstablish": does_not,
        "status": status,
    }
    if aliases:
        item["aliases"] = aliases
    if notes:
        item["notes"] = notes
    return item


CLAIMS = [
    claim(
        "CORE.SCHEMA.STRUCTURE",
        title="Decision-record schema structure",
        proposition="The selected decision record satisfies the selected schema profile's structural rules that were executed.",
        module="core-conformance",
        profiles=["grant-decision-record/0.1", "grant-decision-record/0.2"],
        checks=["core.schema"],
        evidence=["decision-record"],
        does_not=[
            "truth or completeness of cited evidence",
            "quality of substantive judgment",
            "institutional legitimacy",
        ],
    ),
    claim(
        "CORE.CONFORMANCE.CROSS_FIELD",
        title="Declared cross-field consistency",
        proposition="The selected decision record satisfies the v0.1 semantic conformance rules that were executed.",
        module="core-conformance",
        profiles=["grant-decision-record/0.1"],
        checks=["core.conformance"],
        evidence=["decision-record"],
        does_not=[
            "truth or completeness of cited evidence",
            "quality of substantive judgment",
            "institutional legitimacy",
        ],
    ),
    claim(
        "CORE.AUTHORITY.HUMAN_SURFACE",
        title="Human or collective authority surface",
        proposition="Non-pending decisions identify a permitted human/committee/DAO authority kind under the selected profile rules that were executed.",
        module="core-conformance",
        profiles=["grant-decision-record/0.1"],
        checks=["core.conformance"],
        evidence=["decision-record"],
        does_not=["that automation approved funding", "institutional legitimacy outside the declared surface"],
    ),
    claim(
        "CORE.EVIDENCE.REFERENCE_RESOLUTION",
        title="Evidence reference resolution",
        proposition="Referenced evidence, evaluator, conflict, and delivery identifiers resolve within the decision record under the executed conformance rules.",
        module="core-conformance",
        profiles=["grant-decision-record/0.1"],
        checks=["core.conformance"],
        evidence=["decision-record"],
        does_not=["truth of cited evidence bytes or URIs", "completeness of the underlying evidence set"],
    ),
    claim(
        "CORE.CONFLICT.RECUSAL_CONSISTENCY",
        title="Conflict and recusal consistency",
        proposition="Declared conflicts, recusals, and substitutions are internally consistent under the executed conformance rules.",
        module="core-conformance",
        profiles=["grant-decision-record/0.1"],
        checks=["core.conformance"],
        evidence=["decision-record"],
        does_not=["completeness of undisclosed conflicts", "correctness of conflict judgments"],
    ),
    claim(
        "CORE.CHALLENGE.LIFECYCLE",
        title="Challenge lifecycle consistency",
        proposition="Challenge fields are internally consistent under the executed conformance rules.",
        module="core-conformance",
        profiles=["grant-decision-record/0.1"],
        checks=["core.conformance"],
        evidence=["decision-record"],
        does_not=["that a challenge process was adequate or used", "absence of private correction routes"],
    ),
    claim(
        "CORE.DELIVERY.CONDITION_CONSISTENCY",
        title="Delivery-condition consistency",
        proposition="Delivery conditions required by the decision status are present and reference-consistent under the executed conformance rules.",
        module="core-conformance",
        profiles=["grant-decision-record/0.1"],
        checks=["core.conformance"],
        evidence=["decision-record"],
        does_not=["delivery completion", "payment or settlement"],
    ),
    claim(
        "SOURCE.BYTES.MATCH_METADATA",
        title="Source bytes match metadata",
        proposition="Exact supplied source bytes match the declared content hash and length in the source-artifact metadata.",
        module="source-artifacts",
        profiles=["source-artifact/1"],
        checks=["source.bytes"],
        evidence=["source-artifact-metadata", "source-bytes"],
        does_not=[
            "truth or ownership of the source",
            "adoption of the source by a program",
            "independent capture-time authenticity beyond the supplied metadata",
        ],
    ),
    claim(
        "SOURCE.POLICY_PIN.MATCH",
        title="Policy pin matches byte-verified artifact",
        proposition="A policy pin matches an exact byte-verified source artifact by URI and hash under the executed pin checks.",
        module="source-artifacts",
        profiles=["grant-decision-record/0.2", "source-artifact/1"],
        checks=["source.policy-pins"],
        evidence=["decision-record", "source-artifact-metadata", "source-bytes"],
        does_not=["that the pinned policy is the only applicable policy", "institutional adoption"],
    ),
    claim(
        "PHASE2.C1.MANIFEST_BINDING",
        title="Manifest binding (C1)",
        proposition=phase2_claims.C1_ESTABLISHED,
        module="phase2",
        profiles=["phase2/bundle-2", "phase2/bundle-3"],
        checks=["phase2.c1"],
        evidence=["phase2-evidence-bundle"],
        does_not=[phase2_claims.C1_DOES_NOT],
        aliases=["C1"],
    ),
    claim(
        "PHASE2.C2.TEMPORAL_PRECEDENCE",
        title="Temporal precedence (C2)",
        proposition=phase2_claims.C2_ESTABLISHED,
        module="phase2",
        profiles=["phase2/bundle-2", "phase2/bundle-3"],
        checks=["phase2.c2"],
        evidence=["phase2-evidence-bundle"],
        does_not=[phase2_claims.C2_DOES_NOT],
        aliases=["C2"],
        trust=["selected-anchor-profile-trust-root"],
    ),
    claim(
        "PHASE2.C3.ROUND_ENVELOPE_BINDING",
        title="Round-envelope binding (C3)",
        proposition=phase2_claims.C3_ESTABLISHED,
        module="phase2",
        profiles=["phase2/bundle-2", "phase2/bundle-3"],
        checks=["phase2.c3"],
        evidence=["phase2-evidence-bundle"],
        does_not=[phase2_claims.C3_DOES_NOT],
        aliases=["C3"],
        trust=["selected-anchor-profile-trust-root"],
    ),
    claim(
        "PHASE2.C4.RUN_ATTRIBUTION",
        title="Run attribution (C4)",
        proposition=phase2_claims.C4_ESTABLISHED,
        module="phase2",
        profiles=["phase2/bundle-2", "phase2/bundle-3"],
        checks=["phase2.c4"],
        evidence=["phase2-evidence-bundle"],
        does_not=[
            phase2_claims.C4_DOES_NOT,
            "that the signing key is authorized by an external operator policy (see C4A)",
        ],
        aliases=["C4"],
        notes="C4 remains signature attribution to the supplied key. Authorization is C4A.",
    ),
    claim(
        "PHASE2.C4A.AUTHORIZED_SIGNER",
        title="Authorized run signer (C4A)",
        proposition=(
            "The verified run signature key/identity is authorized by the external verifier "
            "trust policy for the declared operator role within the policy validity window."
        ),
        module="phase2",
        profiles=["phase2/bundle-2", "phase2/bundle-3", "trust-policy/1"],
        checks=["phase2.c4a"],
        evidence=["phase2-evidence-bundle", "external-trust-policy"],
        does_not=[
            "operator honesty or that the committed configuration was used",
            "institutional funding authority",
            "C4 signature attribution when no signature is present",
        ],
        aliases=["C4A"],
        trust=["external-trust-policy"],
        notes="New claim; does not silently strengthen historical C4.",
    ),
    claim(
        "PHASE2.C5.REPLAY_EVIDENCE",
        title="Replay evidence (C5)",
        proposition=phase2_claims.C5_ESTABLISHED,
        module="phase2",
        profiles=["phase2/bundle-2", "phase2/bundle-3"],
        checks=["phase2.c5"],
        evidence=["phase2-evidence-bundle"],
        does_not=[phase2_claims.C5_DOES_NOT],
        aliases=["C5"],
    ),
    claim(
        "PHASE2.C6.HUMAN_AUTHORITY_SEPARATION",
        title="Human authority separation (C6)",
        proposition=phase2_claims.C6_ESTABLISHED,
        module="phase2",
        profiles=["phase2/bundle-2", "phase2/bundle-3"],
        checks=["phase2.c6"],
        evidence=["phase2-evidence-bundle"],
        does_not=[phase2_claims.C6_DOES_NOT],
        aliases=["C6"],
    ),
    claim(
        "PROJ.SPEC.STRUCTURE",
        title="Projection spec structure",
        proposition="The projection specification is structurally valid under the selected projection profile.",
        module="projection",
        profiles=["ens-gdi/public-projection/v1", "ens-gdi/public-projection/v2"],
        checks=["projection.spec"],
        evidence=["projection-spec"],
        does_not=["that the projection policy is socially adequate", "source-record correctness"],
    ),
    claim(
        "PROJ.EXEC.DETERMINISTIC",
        title="Deterministic projection execution",
        proposition="Projection execution is deterministic for the supplied confidential source and projection specification under the selected profile.",
        module="projection",
        profiles=["ens-gdi/public-projection/v1", "ens-gdi/public-projection/v2"],
        checks=["projection.execute"],
        evidence=["confidential-record", "projection-spec", "public-projection"],
        does_not=["adequacy of disclosure policy", "absence of dictionary attacks on low-entropy withheld fields"],
    ),
    claim(
        "PROJ.COVERAGE.COMPLETE",
        title="Projection coverage completeness",
        proposition="Every covered source field has a disposition under the selected projection version.",
        module="projection",
        profiles=["ens-gdi/public-projection/v1", "ens-gdi/public-projection/v2"],
        checks=["projection.coverage"],
        evidence=["confidential-record", "projection-spec"],
        does_not=["that withheld material is unknowable", "merit or fairness"],
    ),
    claim(
        "PROJ.WITHHELD.COMMITMENT",
        title="Withheld subtree commitment",
        proposition="Withheld commitments match the supplied confidential subtrees when those subtrees are available for verification under the selected projection version.",
        module="projection",
        profiles=["ens-gdi/public-projection/v2"],
        checks=["projection.withheld"],
        evidence=["confidential-record", "projection-spec", "public-projection"],
        does_not=["secrecy against dictionary attack for low-entropy fields", "source authenticity"],
    ),
    claim(
        "PROJ.INTEGRITY.BIND",
        title="Projection integrity binding",
        proposition="Projection integrity binds the exact specified inputs and outputs under its versioned construction and does not overwrite source integrity.",
        module="projection",
        profiles=["ens-gdi/public-projection/v2"],
        checks=["projection.integrity"],
        evidence=["confidential-record", "projection-spec", "public-projection"],
        does_not=["source-record integrity when separately declared", "institutional approval of the projection policy"],
    ),
    claim(
        "CORPUS.CASE.CONTRACT",
        title="Corpus case contract",
        proposition="The corpus case object is structurally valid under the corpus case schema and protocol rules that were executed.",
        module="corpus",
        profiles=["corpus-case/1"],
        checks=["corpus.case"],
        evidence=["corpus-case"],
        does_not=["source truth", "annotator correctness", "representativeness"],
    ),
    claim(
        "CORPUS.SNAPSHOT.BYTES",
        title="Corpus snapshot byte binding",
        proposition="Exact record snapshot bytes match the declared SHA-256 hashes.",
        module="corpus",
        profiles=["corpus-case/1"],
        checks=["corpus.snapshot-bytes"],
        evidence=["corpus-case", "decision-record-snapshot"],
        does_not=["historical completeness", "merit"],
    ),
    claim(
        "CORPUS.FINDINGS.EXACT",
        title="Corpus validator finding binding",
        proposition="Exact validator findings match the initial and final decision-record bytes under the corpus binding protocol.",
        module="corpus",
        profiles=["corpus-case/1"],
        checks=["corpus.findings"],
        evidence=["corpus-case", "decision-record-snapshot"],
        does_not=["that unresolved findings are process gaps", "fairness"],
    ),
    claim(
        "CORPUS.SOURCE.REDISTRIBUTABLE_ONLY",
        title="Redistributable source byte verification",
        proposition="Source-artifact byte verification is claimed only for redistributable supplied bytes.",
        module="corpus",
        profiles=["corpus-case/1"],
        checks=["corpus.sources"],
        evidence=["corpus-case"],
        does_not=["that reference-only URIs are false", "authorized-audit completeness"],
    ),
    claim(
        "CORPUS.METRICS.ARITHMETIC",
        title="Corpus metrics arithmetic",
        proposition="Reported corpus metrics are arithmetically correct for the supplied case annotations and findings.",
        module="corpus",
        profiles=["corpus-case/1"],
        checks=["corpus.metrics"],
        evidence=["corpus-case"],
        does_not=["agreement equals correctness", "study readiness equals representativeness"],
    ),
    claim(
        "CORPUS.STUDY.GATES",
        title="Study-status machine gates",
        proposition="Study-status machine gates are computed correctly against the predeclared study plan.",
        module="corpus",
        profiles=["corpus-study-plan/1"],
        checks=["corpus.study-status"],
        evidence=["study-plan", "corpus-cases"],
        does_not=[
            "that uncovered strata have no evidence anywhere",
            "that ready-for-final-review means the research is complete",
        ],
    ),
    claim(
        "FUNDING.STATUS.SNAPSHOT",
        title="Funding decision-status snapshot",
        proposition="A dated decision-status snapshot matches the cited artifact set under the funding provenance rules that were executed.",
        module="funding",
        profiles=["funding-provenance/1"],
        checks=["funding.status-snapshot"],
        evidence=["funding-status-snapshot"],
        does_not=["payment", "transfer", "receipt", "settlement", "work completion"],
    ),
    claim(
        "FUNDING.FINANCIAL.SEPARATE_EVIDENCE",
        title="Financial evidence requires its own source",
        proposition="Financial-evidence fields are populated only when their own evidence is supplied; allocation alone does not establish payment, receipt, or settlement.",
        module="funding",
        profiles=["funding-provenance/1"],
        checks=["funding.financial-evidence"],
        evidence=["funding-status-snapshot"],
        does_not=["that unpaid means the event never occurred elsewhere"],
    ),
    claim(
        "RELEASE.COMMIT.IDENTITY",
        title="Release commit identity",
        proposition="The release artifact set identifies an exact repository commit.",
        module="release",
        profiles=["release-integrity/1"],
        checks=["release.commit"],
        evidence=["release-manifest"],
        does_not=["byte-reproducible builds unless independently demonstrated"],
    ),
    claim(
        "RELEASE.CHECKS.CORRESPOND",
        title="Release checks correspond to commit",
        proposition="Required validation checks correspond to the exact published commit under the release integrity procedure that was executed.",
        module="release",
        profiles=["release-integrity/1"],
        checks=["release.checks"],
        evidence=["release-manifest", "ci-run-record"],
        does_not=["substantive correctness of the software", "institutional endorsement"],
    ),
    claim(
        "RELEASE.ARCHIVE.DIGEST",
        title="Attached archive digest",
        proposition="The attached release archive digest matches the attached bytes under the release integrity procedure that was executed.",
        module="release",
        profiles=["release-integrity/1"],
        checks=["release.archive-digest"],
        evidence=["release-archive", "sha256-manifest"],
        does_not=["that downstream mirrors remain unmodified forever"],
    ),
    claim(
        "RELEASE.SBOM.PIPELINE",
        title="SBOM pipeline claim boundary",
        proposition="SBOM and attestation artifacts claim only what the build pipeline establishes for the exact published assets.",
        module="release",
        profiles=["release-integrity/1"],
        checks=["release.sbom"],
        evidence=["sbom"],
        does_not=["absence of all vulnerabilities", "runtime supply-chain integrity after download"],
    ),
    claim(
        "TRUST.POLICY.EXTERNAL",
        title="External trust policy binding",
        proposition="Trust-dependent checks used an externally supplied trust policy whose digest is recorded; the bundle did not appoint its own trust roots.",
        module="trust",
        profiles=["trust-policy/1"],
        checks=["trust.policy"],
        evidence=["external-trust-policy"],
        does_not=["correctness of the operator's trust choices", "universal public trust"],
    ),
]


def main() -> None:
    ids = [item["claimId"] for item in CLAIMS]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate claim IDs")
    out = {"registryVersion": "1", "claims": CLAIMS}
    path = ROOT / "claims" / "claim-registry.v1.json"
    path.write_bytes((json.dumps(out, indent=2, ensure_ascii=False) + "\n").encode("utf-8"))
    print(f"wrote {path} ({len(CLAIMS)} claims)")


if __name__ == "__main__":
    main()
